version: "3"
services:

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db

  gatekeeper:
    build:
      context: .
      dockerfile: Dockerfile.gatekeeper
    image: keychainmdip/gatekeeper
    environment:
      - KC_GATEKEEPER_DB=json
      - KC_MONGODB_URL=mongodb://mongodb:27017
    volumes:
      - ./data:/app/data
    ports:
      - "4224:4224"
    depends_on:
      - mongodb

  hyperswarm:
    build:
      context: .
      dockerfile: Dockerfile.hyperswarm
    image: keychainmdip/hyperswarm-mediator
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper
      - KC_GATEKEEPER_PORT=4224
      - KC_NODE_NAME=${KC_NODE_NAME}
    volumes:
      - ./data:/app/data
    depends_on:
      - gatekeeper

  tess-node:
    image: macterra/tesseract-node:v21.08.03
    ports:
      - "7333:7333"
      - "8333:8333"
    volumes:
      - ./data/tesseract:/data

  tess-mediator:
    build:
      context: .
      dockerfile: Dockerfile.tess
    image: keychainmdip/tess-mediator
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper
      - KC_GATEKEEPER_PORT=4224
      - KC_TESS_HOST=tess-node
      - KC_TESS_PORT=8333
      - KC_TESS_USER=${KC_TESS_USER}
      - KC_TESS_PASS=${KC_TESS_PASS}
      - KC_TESS_ID=${KC_TESS_ID}
    volumes:
      - ./data:/app/data
    depends_on:
      - gatekeeper
      - tess-node

  btc-mediator:
    build:
      context: .
      dockerfile: Dockerfile.btc
    image: keychainmdip/btc-mediator
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper
      - KC_GATEKEEPER_PORT=4224
      - KC_NODE_ID=${KC_NODE_ID}
      - KC_BTC_HOST=172.17.0.1
      - KC_BTC_PORT=${KC_BTC_PORT}
      - KC_BTC_USER=${KC_BTC_USER}
      - KC_BTC_PASS=${KC_BTC_PASS}
    volumes:
      - ./data:/app/data
    depends_on:
      - gatekeeper
