version: "3"
services:

  gatekeeper:
    build:
      context: .
      dockerfile: Dockerfile.gatekeeper
    image: keychainmdip/gatekeeper
    environment:
      - KC_GATEKEEPER_DB=mongodb
      - KC_MONGODB_URL=mongodb://mongodb:27017
    volumes:
      - ./data:/app/data
    ports:
      - "4224:4224"
    depends_on:
      - mongodb

  hyperswarm:
    build:
      context: .
      dockerfile: Dockerfile.hyperswarm
    image: keychainmdip/hyperswarm-mediator
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper
      - KC_GATEKEEPER_PORT=4224
      - KC_GATEKEEPER_DB=mongodb
      - KC_MONGODB_URL=mongodb://mongodb:27017
      - KC_NODE_NAME=${KC_NODE_NAME}
    volumes:
      - ./data:/app/data
    depends_on:
      - gatekeeper

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
