services:

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db

  gatekeeper:
    build:
      context: .
      dockerfile: Dockerfile.gatekeeper
    image: keychainmdip/gatekeeper
    environment:
      - KC_GATEKEEPER_DB=json
      - KC_GATEKEEPER_REGISTRIES=hyperswarm,TESS
      - KC_MONGODB_URL=mongodb://mongodb:27017
    volumes:
      - ./data:/app/data
    ports:
      - "4224:4224"
    depends_on:
      - mongodb

  keymaster:
    build:
      context: .
      dockerfile: Dockerfile.keymaster
    image: keychainmdip/keymaster
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper
      - KC_GATEKEEPER_PORT=4224
    volumes:
      - ./data:/app/data
    ports:
      - "4226:4226"
    depends_on:
      - gatekeeper

  hyperswarm:
    build:
      context: .
      dockerfile: Dockerfile.hyperswarm
    image: keychainmdip/hyperswarm-mediator
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper
      - KC_GATEKEEPER_PORT=4224
      - KC_NODE_NAME=${KC_NODE_NAME}
    volumes:
      - ./data:/app/data
    depends_on:
      - gatekeeper

  tess-node:
    image: macterra/tesseract-node:v21.08.03
    ports:
      - "7333:7333"
      - "8333:8333"
    volumes:
      - ./data/tesseract:/data

  tess-mediator:
    build:
      context: .
      dockerfile: Dockerfile.sat
    image: keychainmdip/sat-mediator
    environment:
      - KC_GATEKEEPER_URL=http://gatekeeper
      - KC_GATEKEEPER_PORT=4224
      - KC_NODE_ID=${KC_NODE_ID}
      - KC_SAT_CHAIN=TESS
      - KC_SAT_NETWORK=mainnet
      - KC_SAT_START_BLOCK=142865
      - KC_SAT_HOST=tess-node
      - KC_SAT_PORT=8333
      - KC_SAT_USER=${KC_TESS_USER}
      - KC_SAT_PASS=${KC_TESS_PASS}
      - KC_SAT_WALLET=${KC_TESS_WALLET}
      - KC_SAT_IMPORT_INTERVAL=${KC_TESS_IMPORT_INTERVAL}
      - KC_SAT_EXPORT_INTERVAL=${KC_TESS_EXPORT_INTERVAL}
      - KC_SAT_FEE_MIN=${KC_TESS_FEE_MIN}
      - KC_SAT_FEE_MAX=${KC_TESS_FEE_MAX}
      - KC_SAT_FEE_INC=${KC_TESS_FEE_INC}
    volumes:
      - ./data:/app/data
    depends_on:
      - gatekeeper
      - tess-node
