# syntax=docker/dockerfile:1

FROM node:22.15.0-bullseye-slim AS builder

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY services/mediators/satoshi-inscription/package*.json ./satoshi/
COPY services/mediators/satoshi-inscription/patches/ ./satoshi/patches/

RUN --mount=type=cache,target=/root/.npm npm ci --ignore-scripts
RUN --mount=type=cache,target=/root/.npm cd satoshi && npm ci

COPY services/mediators/satoshi-inscription ./satoshi/

RUN npm rebuild sqlite3
RUN npm run build
RUN cd satoshi && npm run build

FROM node:22.15.0-bullseye-slim

WORKDIR /app
COPY --from=builder /app /app

WORKDIR /app/satoshi

CMD ["node", "dist/inscription-mediator.js"]
