services:

  tess-node:
    image: macterra/tesseract-node:v21.08.03
    ports:
      - "7333:7333"
      - "8333:8333"
    volumes:
      - ./data/tesseract:/data
    user: "${KC_UID}:${KC_GID}"

  tess-mediator:
    build:
      context: .
      dockerfile: Dockerfile.sat
    image: keychainmdip/sat-mediator
    network_mode: host
    environment:
      - KC_GATEKEEPER_URL=http://localhost
      - KC_GATEKEEPER_PORT=4224
      - KC_NODE_ID=${KC_NODE_ID}
      - KC_SAT_CHAIN=TESS
      - KC_SAT_NETWORK=mainnet
      - KC_SAT_START_BLOCK=142865
      - KC_SAT_HOST=localhost
      - KC_SAT_PORT=8333
      - KC_SAT_USER=${KC_TESS_USER}
      - KC_SAT_PASS=${KC_TESS_PASS}
      - KC_SAT_WALLET=${KC_TESS_WALLET}
      - KC_SAT_IMPORT_INTERVAL=${KC_TESS_IMPORT_INTERVAL}
      - KC_SAT_EXPORT_INTERVAL=${KC_TESS_EXPORT_INTERVAL}
      - KC_SAT_FEE_MIN=${KC_TESS_FEE_MIN}
      - KC_SAT_FEE_MAX=${KC_TESS_FEE_MAX}
      - KC_SAT_FEE_INC=${KC_TESS_FEE_INC}
    volumes:
      - ./data:/app/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - tess-node
