# syntax=docker/dockerfile:1

FROM node:22.15.0-bullseye-slim AS builder

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY services/keymaster/client/package*.json ./keymaster/client/
COPY services/keymaster/server/package*.json ./keymaster/server/

RUN --mount=type=cache,target=/root/.npm npm ci --ignore-scripts
RUN --mount=type=cache,target=/root/.npm cd keymaster/client && npm ci --include=dev
RUN --mount=type=cache,target=/root/.npm cd keymaster/server && npm ci

COPY services/keymaster ./keymaster/

RUN npm rebuild sqlite3
RUN npm run build
RUN cd keymaster/client && npm run build
RUN cd keymaster/server && npm run build

FROM node:22.15.0-bullseye-slim

WORKDIR /app
COPY --from=builder /app /app

WORKDIR /app/keymaster

CMD ["node", "server/dist/keymaster-api.js"]
