# Use the official Node.js as the base image
FROM node:22.15.0-bullseye-slim

# Set the working directory
WORKDIR /app

# Copy packages
COPY package*.json ./
COPY packages/ ./packages/
COPY services/search-server ./search-server/

# Install dependencies
RUN npm ci
RUN npm run build

# Make sure dir is owned by user who will build
RUN chown -R node:node /app/search-server

# Switch to node user
USER node

WORKDIR /app/search-server

RUN npm i

EXPOSE 3001

# Run...
CMD ["npm", "start"]

