# Use the official Node.js as the base image
FROM node:18.20.8-bullseye-slim

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY packages/ ./packages/

# Install dependencies
RUN npm ci
RUN npm run build

COPY services/mediators/satoshi ./satoshi/
WORKDIR /app/satoshi
RUN npm ci && npm run build

# Run...
CMD ["node", "dist/satoshi-mediator.js"]
