# Use the official Node.js as the base image
FROM node:18.15.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy app
COPY *.js ./

# Run...
CMD ["node", "tess-mediator.js"]
