services:
  tbtc-mediator:
    build:
      context: .
      dockerfile: Dockerfile.sat
    image: keychainmdip/sat-mediator
    network_mode: host
    environment:
      - KC_GATEKEEPER_URL=http://localhost
      - KC_GATEKEEPER_PORT=4224
      - KC_NODE_ID=${KC_NODE_ID}
      - KC_SAT_CHAIN=TBTC
      - KC_SAT_NETWORK=testnet
      - KC_SAT_START_BLOCK=38000
      - KC_SAT_HOST=${KC_TBTC_HOST}
      - KC_SAT_PORT=${KC_TBTC_PORT}
      - KC_SAT_USER=${KC_TBTC_USER}
      - KC_SAT_PASS=${KC_TBTC_PASS}
      - KC_SAT_WALLET=${KC_TBTC_WALLET}
      - KC_SAT_IMPORT_INTERVAL=${KC_TBTC_IMPORT_INTERVAL}
      - KC_SAT_EXPORT_INTERVAL=${KC_TBTC_EXPORT_INTERVAL}
      - KC_SAT_FEE_MIN=${KC_TBTC_FEE_MIN}
      - KC_SAT_FEE_MAX=${KC_TBTC_FEE_MAX}
      - KC_SAT_FEE_INC=${KC_TBTC_FEE_INC}
    volumes:
      - ./data:/app/data
