services:
  tbtc-node:
    image: macterra/bitcoin-core:v27.99.0-2f7d9aec4d04
    volumes:
      - ./data/tbtc:/root/.bitcoin
    ports:
      - "48333:48333"
      - "48332:48332"

  tbtc-mediator:
    build:
      context: .
      dockerfile: Dockerfile.sat
    image: keychainmdip/sat-mediator
    network_mode: host
    environment:
      - KC_GATEKEEPER_URL=http://localhost
      - KC_GATEKEEPER_PORT=4224
      - KC_NODE_ID=${KC_NODE_ID}
      - KC_SAT_CHAIN=TBTC
      - KC_SAT_NETWORK=testnet
      - KC_SAT_HOST=localhost
      - KC_SAT_PORT=48332
      - KC_SAT_START_BLOCK=${KC_TBTC_START_BLOCK}
      - KC_SAT_USER=${KC_TBTC_USER}
      - KC_SAT_PASS=${KC_TBTC_PASS}
      - KC_SAT_WALLET=${KC_TBTC_WALLET}
      - KC_SAT_IMPORT_INTERVAL=${KC_TBTC_IMPORT_INTERVAL}
      - KC_SAT_EXPORT_INTERVAL=${KC_TBTC_EXPORT_INTERVAL}
      - KC_SAT_FEE_MIN=${KC_TBTC_FEE_MIN}
      - KC_SAT_FEE_MAX=${KC_TBTC_FEE_MAX}
      - KC_SAT_FEE_INC=${KC_TBTC_FEE_INC}
    volumes:
      - ./data:/app/data
    user: "${KC_UID}:${KC_GID}"
    depends_on:
      - tbtc-node
