#!/usr/bin/env bash
set -e
source .env
set +a

DOCKER_OPTIONS=""

while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -d)
        DOCKER_OPTIONS="$DOCKER_OPTIONS -d"
        shift # past argument
        ;;
        *)    # unknown option
        shift # past argument
        ;;
    esac
done

docker compose build

if [ "$KC_TESS_ENABLED" = "true" ]; then
    echo "Starting Tesseract (TESS) mediator"
    docker compose -p tess -f docker-compose.tess.yml up -d
else
    echo "TESS mediator disabled"
fi

if [ "$KC_TFTC_ENABLED" = "true" ]; then
    echo "Starting Feathercoin testnet (TFTC) mediator"
    docker compose -p tftc -f docker-compose.tftc.yml up -d
else
    echo "TFTC mediator disabled"
fi

if [ "$KC_TBTC_ENABLED" = "true" ]; then
    echo "Starting Bitcoin testnet4 (TBTC) mediator"
    docker compose -p tbtc -f docker-compose.tbtc.yml up -d
else
    echo "TBTC mediator disabled"
fi

docker compose up $DOCKER_OPTIONS
