#!/usr/bin/env bash
set -e

COMPOSE_FILE="docker-compose.hyperswarm.yml"
DOCKER_OPTIONS=""

while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -r|--registry)
        REGISTRY="$2"
        shift # past argument
        shift # past value
        ;;
        -d)
        DOCKER_OPTIONS="$DOCKER_OPTIONS -d"
        shift # past argument
        ;;
        *)    # unknown option
        shift # past argument
        ;;
    esac
done

if [ "$REGISTRY" = "TESS" ]; then
    COMPOSE_FILE="docker-compose.tess.yml"
elif [ "$REGISTRY" = "TBTC" ]; then
    COMPOSE_FILE="docker-compose.tbtc.yml"
fi

echo "$COMPOSE_FILE" > last-compose-file.txt

docker compose -f $COMPOSE_FILE build
docker compose -f $COMPOSE_FILE up $DOCKER_OPTIONS
