#!/bin/bash

set -e

# Change to the project root, assuming the script is in ./scripts/
cd "$(git rev-parse --show-toplevel)"

touch .env

ENV_FILE=".env"

echo "Generating .env file at project root..."

cat > "$ENV_FILE" <<EOL
# Auto-generated .env file

# General
KC_UID=1000
KC_GID=1000
KC_NODE_NAME=mdip-quality
KC_NODE_ID=mdip-quality
KC_MDIP_PROTOCOL=/MDIP/test


# Gatekeeper
KC_GATEKEEPER_PORT=4224
KC_GATEKEEPER_DID_PREFIX=did:test
KC_GATEKEEPER_DB=redis
KC_GATEKEEPER_REGISTRIES=local
KC_GATEKEEPER_GC_INTERVAL=60
KC_GATEKEEPER_STATUS_INTERVAL=1
KC_GATEKEEPER_SERVE_CLIENT=true

# Keymaster
KC_KEYMASTER_PORT=4226
KC_KEYMASTER_DB=redis
KC_ENCRYPTED_PASSPHRASE=passphrase
KC_KEYMASTER_SERVE_CLIENT=true
KC_WALLET_CACHE=false
KC_DEFAULT_REGISTRY=local
KC_DISABLE_SEARCH=true

# CLI
KC_GATEKEEPER_URL=http://localhost:4224
KC_KEYMASTER_URL=http://localhost:4226

# Hyperswarm
KC_HYPR_EXPORT_INTERVAL=2
KC_MDIP_PROTOCOL=/MDIP/testing

# Bitcoin mediator
KC_BTC_HOST=localhost
KC_BTC_CHAIN=BTC
KC_BTC_NETWORK=bitcoin
KC_BTC_START_BLOCK=927970
KC_BTC_PORT=8332
KC_BTC_USER=bitcoin
KC_BTC_PASS=bitcoin
KC_BTC_WALLET=mdip
KC_BTC_IMPORT_INTERVAL=1
KC_BTC_EXPORT_INTERVAL=1
KC_BTC_FEE_BLOCK_TARGET=1
KC_BTC_FEE_FALLBACK_SAT_BYTE=10
KC_BTC_FEE_MAX=0.00010000
KC_BTC_RBF_ENABLED=true
KC_BTC_REIMPORT=true
KC_BTC_DB=json

# Bitcoin testnet4 mediator
KC_TBTC_HOST=localhost
KC_TBTC_CHAIN=TBTC
KC_TBTC_NETWORK=testnet
KC_TBTC_START_BLOCK=38000
KC_TBTC_PORT=48332
KC_TBTC_USER=testnet4
KC_TBTC_PASS=testnet4
KC_TBTC_WALLET=mdip
KC_TBTC_IMPORT_INTERVAL=1
KC_TBTC_EXPORT_INTERVAL=1
KC_TBTC_FEE_BLOCK_TARGET=1
KC_TBTC_FEE_FALLBACK_SAT_BYTE=10
KC_TBTC_FEE_MAX=0.00000600
KC_TBTC_RBF_ENABLED=false
KC_TBTC_REIMPORT=true
KC_TBTC_DB=json

# Feathercoin testnet mediator
KC_TFTC_HOST=localhost
KC_TFTC_START_BLOCK=0
KC_TFTC_PORT=19337
KC_TFTC_USER=feathercoin
KC_TFTC_PASS=feathercoin
KC_TFTC_WALLET=mdip
KC_TFTC_IMPORT_INTERVAL=1
KC_TFTC_EXPORT_INTERVAL=1
KC_TFTC_FEE_BLOCK_TARGET=1
KC_TFTC_FEE_FALLBACK_SAT_BYTE=10
KC_TFTC_FEE_MAX=0.00003000
KC_TFTC_RBF_ENABLED=false
KC_TFTC_REIMPORT=true
KC_TFTC_DB=json

# BTC signet mediator
KC_SIGNET_HOST=localhost
KC_SIGNET_START_BLOCK=251900
KC_SIGNET_PORT=38332
KC_SIGNET_USER=signet
KC_SIGNET_PASS=signet
KC_SIGNET_WALLET=mdip
KC_SIGNET_IMPORT_INTERVAL=1
KC_SIGNET_EXPORT_INTERVAL=1
KC_SIGNET_FEE_BLOCK_TARGET=1
KC_SIGNET_FEE_FALLBACK_SAT_BYTE=10
KC_SIGNET_FEE_MAX=0.00003000
KC_SIGNET_RBF_ENABLED=false
KC_SIGNET_REIMPORT=true
KC_SIGNET_DB=json

# BTC signet inscribed mediator
KC_SIGNET_INS_HOST=localhost
KC_SIGNET_INS_START_BLOCK=262868
KC_SIGNET_INS_PORT=38332
KC_SIGNET_INS_USER=signet
KC_SIGNET_INS_PASS=signet
KC_SIGNET_INS_WALLET=mdip
KC_SIGNET_INS_IMPORT_INTERVAL=1
KC_SIGNET_INS_EXPORT_INTERVAL=1
KC_SIGNET_INS_FEE_BLOCK_TARGET=1
KC_SIGNET_INS_FEE_FALLBACK_SAT_BYTE=10
KC_SIGNET_INS_FEE_MAX=0.00200000
KC_SIGNET_INS_RBF_ENABLED=false
KC_SIGNET_INS_REIMPORT=true
KC_SIGNET_INS_DB=json

# IPFS mediator
KC_IPFS_INTERVAL=60
KC_IPFS_BATCH_SIZE=100
KC_IPFS_CONCURRENCY=10

# Optional IPFS Cluster support
KC_IPFS_CLUSTER_URL=""
KC_IPFS_CLUSTER_AUTH_HEADER=""
EOL

echo ".env file created with the following content:"
cat "$ENV_FILE"
