name: Build Chrome Extension

on:
  push:

jobs:
  build-chrome-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node 22.15.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install root dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Install extension dependencies
        run: |
          cd ./apps/chrome-extension
          npm install

      - name: Build extension
        run: |
          cd ./apps/chrome-extension
          npm start

