name: Build Chrome Extension

on:
  push:

jobs:
  build-chrome-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node 18.20.8
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'

      - name: Install root dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Install explorer dependencies
        run: |
          cd ./services/explorer
          npm install

      - name: Build extension
        run: |
          cd ./services/explorer
          npm run build

