# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build & Test Docker images

on:
  pull_request:

jobs:
  build_test_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup env for Testing
        working-directory: ./tests/cli-tests
        run: |
          sudo apt update
          sudo apt-get install -y expect
          ./generate_test_env.sh
          ln -s "$GITHUB_WORKSPACE/kc" /usr/local/bin/kc
          ln -s "$GITHUB_WORKSPACE/admin" /usr/local/bin/admin
          echo "/usr/local/bin" >> $GITHUB_PATH
      

      - name: Run Node
        run: |
          ./start-node-ci cli
          docker compose ps
          sleep 30


      - name: Run cli-tests
        working-directory: ./tests
        env:
          KC_GATEKEEPER_URL: http://localhost:4224
          KC_KEYMASTER_URL: http://localhost:4226
        run: |
          ./run_cli_tests.sh --ci-redis
        

      - name: Grab logs
        if: always()
        run: |
          docker compose logs --no-color keymaster cli gatekeeper redis > docker-compose-logs.txt
          cat docker-compose-logs.txt
      

      - name: Teardown Docker
        run: |
          ./stop-node
      
          
      - name: Upload docker logs & artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-logs
          path: docker-compose-logs.txt
      

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: E2E Artifacts
            path: tests/test-results/cli-tests.xml


