name: 'E2E Test Report'
on:
  workflow_run:
    workflows: ['Build & Test Docker images']                     # runs after Build & Test Docker images workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v2
      with:
        artifact: E2E Artifacts            # artifact name
        name: TCL/Expect Tests                  # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results