name: Generate OpenAPI Docs

on:
  pull_request:

jobs:
  build-openapi-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Use Node 18.20.8
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'

      - name: Install dependencies
        run: npm install

      - name: Generate OpenAPI JSON files
        run: npm run generate-openapi

      - name: Commit generated OpenAPI docs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/gatekeeper-api.json
          git add doc/keymaster-api.json
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "chore: update generated OpenAPI docs" || true
            git push
          fi
